#ifndef SEMANTIC_SYMBOLS
#define SEMANTIC_SYMBOLS

#define SYMBOL_CHAR     2
#define SYMBOL_INTEGER  3
#define SYMBOL_REAL    4
#define SYMBOL_STRING  5
#define SYMBOL_FUNC_INT 7
#define SYMBOL_FUNC_FLOAT 8
#define SYMBOL_FUNC_CHAR 9


#endif
